<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<!-- or .NET version you want to target -->
	</PropertyGroup>

	<ItemGroup>
		<!-- Reference the C++/CLI ScriptAPI DLL -->
		<Reference Include="..\SliceScriptAPI\bin\Debug\ScriptAPI.dll" />
	</ItemGroup>

</Project>